{% set name = "splinkclickhouse" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/splinkclickhouse-{{ version }}.tar.gz
  sha256: f0df99f495be0a0e23716920784522c410c6a83d3e76c3929f1e372203699a17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - splink >=4.0.6
    - clickhouse-connect >=0.7.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - splinkclickhouse

about:
  home: https://github.com/ADBond/splinkclickhouse
  summary: Clickhouse backend support for Splink
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ADBond/splinkclickhouse
  doc_url: https://github.com/ADBond/splinkclickhouse/blob/main/README.md

extra:
  recipe-maintainers:
    - ADBond
