{% set name = "splinkclickhouse" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/splinkclickhouse-{{ version }}.tar.gz
  sha256: 537af05dcf899d6827ed11c9df85f4da067653f8dc872f7500f5b18327263177

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - hatchling
    - pip
  run:
    - python >=3.9,<4.0
    - splink >=4.0.2
    - clickhouse-connect >=0.7.0

test:
  imports:
    - splinkclickhouse

about:
  home: https://github.com/ADBond/splinkclickhouse
  summary: Clickhouse backend support for Splink
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ADBond/splinkclickhouse
  doc_url: https://github.com/ADBond/splinkclickhouse/blob/main/README.md

extra:
  recipe-maintainers:
    - ADBond
